name: Publish the NPM package to the GitHub Package Registry
on:
  push:
    branches:
      - main
jobs:
  build:
    concurrency: publish-internal
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@2pir-ai'
      - run: yarn
      - run: yarn build && (cd dist; yarn publish --access restricted)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
